### ISSUE TITLE
ERROR (BadRequest): Expecting apiKey (HTTP 400)

### ISSUE THREAD

**Issue by janpokrzywinski** [rackerlabs/rackspace-novaclient#13]
Hi,

Version of nova-client:
# nova --version
2.29.0

This was tested on debian 8 and OSX 10.10, after setup and configuring variables (tested with echo to see if present and exported correctly) nova client returns this:
# nova --debug list
REQ: curl -g -i 'https://lon.identity.api.rackspacecloud.com/v2.0/tokens' -X POST -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: python-novaclient" -d '{"auth": {"RAX-KSKEY:apiKeyCredentials": {"username": "<REMOVEDFORSECURITY>", "apiKey": null}}}'
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SecurityWarning
RESP: [400] {'content-encoding': 'gzip', 'transfer-encoding': 'chunked', 'vary': 'Accept, Accept-Encoding, X-Auth-Token', 'x-newrelic-app-data': 'PxQGUF9aDwETVlhSBQYFUkYdFGQHBDcQUQxLA1tMXV1dORYzVBJHNQFUZAQUFVFQVThOFlhaUggXER5jLTU3SxJOCEwIFAQcA1UNUQJVH09VGhUCUVJeCwAFVAACBlMAVwhSET8=', 'server': 'nginx', 'connection': 'keep-alive', 'date': 'Tue, 15 Sep 2015 15:13:44 GMT', 'content-type': 'application/json'}
RESP BODY: null

DEBUG (shell:899) Expecting apiKey (HTTP 400)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/novaclient/shell.py", line 896, in main
    OpenStackComputeShell().main(argv)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/shell.py", line 730, in main
    api_version = api_versions.discover_version(self.cs, api_version)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/api_versions.py", line 253, in discover_version
    client)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/api_versions.py", line 235, in _get_server_version_range
    version = client.versions.get_current()
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v2/versions.py", line 62, in get_current
    return self._get_current()
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v2/versions.py", line 53, in _get_current
    all_versions = self.list()
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v2/versions.py", line 82, in list
    return self._list(version_url, "versions")
  File "/usr/local/lib/python2.7/dist-packages/novaclient/base.py", line 72, in _list
    _resp, body = self.api.client.get(url)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 446, in get
    return self._cs_request(url, 'GET', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 402, in _cs_request
    self.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 557, in authenticate
    auth_url = self._plugin_auth(auth_url)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 625, in _plugin_auth
    return self.auth_plugin.authenticate(self, auth_url)
  File "/usr/local/lib/python2.7/dist-packages/rackspace_auth_openstack/plugin.py", line 21, in authenticate
    _authenticate(cls, auth_url)
  File "/usr/local/lib/python2.7/dist-packages/rackspace_auth_openstack/plugin.py", line 41, in _authenticate
    return cls._authenticate(auth_url, body)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 659, in _authenticate
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 397, in _time_request
    resp, body = self.request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 391, in request
    raise exceptions.from_response(resp, body, url, method)
BadRequest: Expecting apiKey (HTTP 400)
ERROR (BadRequest): Expecting apiKey (HTTP 400)

It looks like there is no API key value sent in the json, shows only "null". When providing login details from the command line with --os-password it also returns 400 response.

Thanks,
Jan

**Comment by coreywright** [comment]
@janpokrzywinski 

this issue is already addressed in #11, specifically see https://github.com/rackerlabs/rackspace-novaclient/issues/11#issuecomment-139029903 which identifies this problem as being upstream (and only revealed by the rackstack auth plugin).

full disclosure: there is an issue in the rackspace api that requests to `/` or `/v2/` fail (401) and the new version of novaclient now exercises that api, so even with the upstream bug fix it'll still fail.

for future reference please review other issues before creating a new one to see if your issue was previously opened and possibly addressed.

**Comment by janpokrzywinski** [comment]
Thank you for the response.
